### ISSUE TITLE
[Feature Request] add clean-up action that triggers when template is used

### ISSUE THREAD

**Issue by LtdSauce** [cpp-best-practices/cpp_boilerplate_project#5]
Hi!

Last year i used a Kotlin project template from Jetbrains for the Advent of Code. It had a nice feature:
After creating my project from the template it automatically committed a clean-up change, that exchanged the template readme with a readme that was more tailored for the project.

Are there any plans to add such thing to this project template? [Here](https://github.com/kotlin-hands-on/advent-of-code-kotlin-template/blob/main/.github/workflows/template-cleanup.yml) is the workflow they used in their project template on github. 

Some things are always bothering me, when i setup my project through the template:

### Static changes
Following things i can think of that always have to change:
- All Badges from the README.md are broken as they point to the project template --> that should be easily fixed with the workflow --> Fixed in #3
- The README.md contains sections that are no longer needed when the template was created --> Fixed in #3
- Rename the "MyProject" to the name of the new github repository --> Fixed in #3

### Dynamic/User changes
Following things could be changed sometimes according to what the user wants. Those are probably not easy, maybe impossible to do:
-  Removing the unwanted examples or dependencies is sometimes anoying because removing one example cannot be done from github directly without branching or multiple commits --> Deprecated because of new template project

- For private projects i'm sometimes not interested in MacOS. Maybe it is possible to disable one or many of the CI Matrix entries? --> not sure if this is sensibel to do

### Apply for help
If this has any chances of beeing excepted i could invest some time in creating the worklfow for at least "fixing" the links of the build badges?

**Comment by LtdSauce** [comment]
@lefticus thanks for merging #3!

My spare time is and was a bit limited to add the remaining points.
For the record the following point remains (as i saw you already have applyed some changes yourself):
- add step that configures cmake to check the janitor has not broken anything
- make janitor able to maintain project templates and create them (see comment above)

**Comment by lefticus** [comment]
I was ready to see it moving forward. I'll keep updating the details as I test out the template for my own tests.
